import Config

# Configure your database
config :crud_app, CrudApp.Repo,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASS"),
  hostname: System.get_env("DB_HOST"),
  database: System.get_env("DB_NAME"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :crud_app, CrudAppWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:crud_app, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:crud_app, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 5432,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :crud_app, CrudAppWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/crud_app_web/router\.ex$",
      ~r"lib/crud_app_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :crud_app, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# ---------------------------------------------------------------------------
# Mailer / Email Configuration (Development)
# ---------------------------------------------------------------------------
#
# Choose ONE of the options below by setting the matching environment variables
# before starting the server.  No new Hex dependencies are required — all
# options use the already-installed `req` HTTP client.
#
# ── Option 1: Brevo (formerly Sendinblue) ──────────────────────────────────
#   export EMAIL_PROVIDER=brevo
#   export BREVO_API_KEY="xkeysib-xxxxxxxxxxxxxxxxxxxx"
#   export SMTP_FROM_EMAIL="your@email.com"
#
# ── Option 2: Mailgun ──────────────────────────────────────────────────────
#   export EMAIL_PROVIDER=mailgun
#   export MAILGUN_API_KEY="key-xxxxxxxxxxxxxxxxxxxxxxxxxx"
#   export MAILGUN_DOMAIN="mg.yourdomain.com"
#   export SMTP_FROM_EMAIL="your@email.com"
#
# ── Option 3: Postmark ─────────────────────────────────────────────────────
#   export EMAIL_PROVIDER=postmark
#   export POSTMARK_API_KEY="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#   export SMTP_FROM_EMAIL="your@email.com"
#
# ── No env vars set → Local mailbox preview at http://localhost:4000/dev/mailbox
# ---------------------------------------------------------------------------

case System.get_env("EMAIL_PROVIDER") do
  "brevo" ->
    config :crud_app, CrudApp.Mailer,
      adapter: Swoosh.Adapters.Brevo,
      api_key: System.get_env("BREVO_API_KEY")

    config :swoosh, :api_client, Swoosh.ApiClient.Req

  "mailgun" ->
    config :crud_app, CrudApp.Mailer,
      adapter: Swoosh.Adapters.Mailgun,
      api_key: System.get_env("MAILGUN_API_KEY"),
      domain: System.get_env("MAILGUN_DOMAIN")

    config :swoosh, :api_client, Swoosh.ApiClient.Req

  "postmark" ->
    config :crud_app, CrudApp.Mailer,
      adapter: Swoosh.Adapters.Postmark,
      api_key: System.get_env("POSTMARK_API_KEY")

    config :swoosh, :api_client, Swoosh.ApiClient.Req

  _ ->
    # Default: Local adapter — view emails at http://localhost:4000/dev/mailbox
    config :crud_app, CrudApp.Mailer, adapter: Swoosh.Adapters.Local
    config :swoosh, :api_client, false
end

